version: '3.10'

services:
  web:
    build: ./
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: