# Generated by Django 5.0.1 on 2024-01-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(verbose_name='Код города')),
                ('city_name', models.CharField(max_length=255, verbose_name='Город')),
                ('temp', models.CharField(max_length=10, verbose_name='Температура')),
                ('wind_speed', models.SmallIntegerField(verbose_name='Скорость ветра')),
                ('country_code', models.CharField(max_length=5, verbose_name='Код страны')),
                ('pressure', models.SmallIntegerField(verbose_name='Давление')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Прогноз погоды',
                'verbose_name_plural': 'Прогноз погоды',
            },
        ),
    ]
